# This is a basic workflow to help you get started with Actions

name: Screenshot Neti

on:

 push:
    branches: [ main ]
    paths:
      - 'screenshot-neti.yml'
      
  pull_request:
    branches: [ main ]
    paths:
      - 'screenshot-neti.yml'
  
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://www.neti.ee
          destination: neti.png

      -  run: ls -lah
